api_platform:
    title: Api Platform Course
    show_webby: false
    version: 1.0.0
    mapping:
        paths:
            - '%kernel.project_dir%/src/Entity'
            - '%kernel.project_dir%/src/Bridge'
    patch_formats:
        jsonapi: [ 'application/vnd.api+json' ]
    formats:
        json: [ 'application/json' ]
        jsonapi: [ 'application/vnd.api+json' ]
        
    error_formats:
        json: [ 'application/json' ]
        jsonapi: [ 'application/vnd.api+json' ]
    
    
    enable_swagger_ui: true
    enable_re_doc: true
    
    swagger:
        versions: [3]
        api_keys:
            JWT:
                name: Authorization
                type: header
    collection:
        pagination:
            page_parameter_name: page
            items_per_page_parameter_name: per_page
    
    # Good cache defaults for REST APIs
    defaults:
        pagination_items_per_page: 30
        pagination_client_items_per_page: true
        pagination_maximum_items_per_page: 100
        standard_put: true
        stateless: true
        normalization_context: 
            skip_null_values: false
        denormalization_context: 
            collect_denormalization_errors: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
            
