# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false
    trusted_proxies: '%env(TRUSTED_PROXIES)%'
    trusted_hosts: '%env(TRUSTED_HOSTS)%'
    # See https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#headers
    trusted_headers: [ 'x-forwarded-for', 'x-forwarded-proto' ]

    #esi: true
    #fragments: true
    php_errors:
        log: true
    
    http_client:
        scoped_clients:
            duolingo.client:
                base_uri: '%env(DUOLINGO_API_URL)%'
                headers:
                  User-Agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.143 Safari/537.36"




when@test:
    framework:
        test: true
