gesdinet_jwt_refresh_token:
    refresh_token_class: App\Entity\RefreshToken
    return_expiration: true
    token_parameter_name: refreshToken
    return_expiration_parameter_name: refreshTokenExpiration
